HW6
SPBSTU-Mobile-development-courses/ios pull request #63
Opened 2020-05-14 19:07 UTC by panandafog

2020-05-28 20:36 UTC, MortyMerr commented
@panandafog напомни, все готово? Можно смотреть?

2020-05-28 21:38 UTC, panandafog commented
> @panandafog напомни, все готово? Можно смотреть?

Это какой-то тонкий намек на то, что я что-то забыл сделать?)

2020-06-02 09:58 UTC, M0rtyMerr requested changes
Хвалю за полноту задания, но небольшие недоработки есть

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/DetailViewController.swift
> +        var textField: String = "tags: "
Предпочитай иммутабельные переменные мутабельным - всегда. Например здесь лучше обойтись
`descriptionTags.text = "tags: \(post.tagsNames)"

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/MainViewController.swift
> +        searchController.searchResultsUpdater = self
Это конечно субъективно, но когда очень много кода конфигурации UI элементов в viewDidLoad, становится трудно читать. Например здесь у тебя и navigationItem и searchController и getData.
Я бы вынес в воспомогательный приватный метод типа `setupUI` все, что связано с разовой настройкой UI

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/MainViewController.swift
> +        //if !activity.isAnimating { activity.startAnimating() }
Удаляй закоменченный код

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/MainViewController.swift
> +        }
let post = isFiltering ? filteredPosts[indexPath.row] : posts[indexPath.row]

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/MainViewController.swift
> +        }
Тоже можно в одну строку и без мутации
Кстати, если не нравится тернарный оператор, можно оставить if, но поменяй let post, на var post. Компилятор понимает, что переменная будет проинициализирована и норм работает

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/MainViewController.swift
> +        self.tableView.reload(changes: changes, section: 0, replacementAnimation: UITableView.RowAnimation.none, updateData: {
trailing closure syntax? линтер точно работает?

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/MainViewController.swift
> +            return
А можно это как нибудь с guard переписать и уменьшить вложенность?

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/MainViewController.swift
> +        guard let bar = searchController.searchBar.text else { return }
можно в один guard добавлять условия через запятую

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/SelfScalingUIImageView.swift
> +    override var intrinsicContentSize: CGSize {
А без этого точно не работает? :) Мне кажется такую задачу можно на констрейнтах решить

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Model/Page.swift
> +    var data: [Post]?
var в моделях данных - плохо

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Model/Post.swift
> +        var tagsStr = ""
Вроде кому-то уже показывал метод `joined(separator:)`. Сам разберешься?

2020-06-02 09:58 UTC, MortyMerr commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/MemesTests/MemeRealmTests.swift
> +        guard let post = post, let realm = realm, let tagsStr = tagsStr else {
В тестах можно форс анврапить. ты уверен, что если post и realm nil, то return - это корректное завершение теста?

2020-06-09 11:37 UTC, panandafog commented on 2020-spring/Pantyuhin Andrey & Khismatullin Kamil/HW6/Memes/memes/Memes/Controller/SelfScalingUIImageView.swift
> +    override var intrinsicContentSize: CGSize {
Наверняка, но мы полдня гуглили и нашли только такой способ
Мне бы тоже было интересно, как это сделать при помощи констрейнтов

2020-06-10 19:57 UTC, merged

2026-07-29 12:15 UTC, Makistos111 reviewed
Нет брейка по ветка FalterPower и PaymentResponse, продебажжил новую ветку с параметрами NoResponse и дал коммит

2026-07-29 12:16 UTC, Makistos111 commented
Также добавил метод IApplicationDelegate для оптимизации старой ветки, чек в Redis, если нужно переставьте, сделал дебаг

2026-07-29 12:19 UTC, Makistos111 commented
Добавил коммит по новой функции, также чек в Pull_Request